#!/usr/bin/env python3
# 
# (c) Copyright RIFT.io, 2013-2016, All Rights Reserved
#
# Author(s): Max Beckett
# Creation Date: 2/16/2016
# 

import logging 
import enum
import time
import sys
import argparse

from rift.watchdog import(
    WatchdogConnector,
)

class Testing(enum.Enum):
    foo = '1'
    bar = '2'

mapping = {
    Testing.foo.value : "foo",
    Testing.bar.value : "bar",
}

log = logging.getLogger("testing")
connector = WatchdogConnector(log, "testing", mapping)
connector.connect()

parser = argparse.ArgumentParser()
parser.add_argument(
    "--send-value",
    required=False,
    default=Testing.foo.value,
    type=str,
    help="value to send to watchdog"
)
arguments = parser.parse_args()


print("send")
while True:    
    connector.write(arguments.send_value)
    time.sleep(1)
