#!/bin/bash

if [ -z "$RIFT_INSTALL" ]; then
   rift_install="/"
else
   rift_install=$RIFT_INSTALL
fi

zsh_bin="${rift_install}/usr/bin/zsh"
zsh_cmd=${zsh_bin}

while [[ $# > 0 ]]
do
  arg=$1
  case $arg in
    --trace_level | --netconf_host | --netconf_port | --username | --passwd)
      zsh_cmd="${zsh_cmd} $1 $2"
      shift 2
    ;;
    --netconf)
      if [ -n "${rwmsg}" ]; then
         echo "Netconf mode and rwmsg mode cannot be specified together"
         exit 1
      fi
      netconf=1
      shift
    ;;
    --schema_listing)
      schema_listing=$2
      zsh_cmd="${zsh_cmd} $1 $2"
      shift 2
      while [[ $# > 0 ]]
      do
        if [[ $1 == "--"* ]]; then
           break 
        fi 
        schema_listing="${schema_listing} $1"
        shift 1
      done
    ;;
    --rwmsg)
      if [ -n "${netconf}" ]; then
         echo "Netconf mode and rwmsg mode cannot be specified together"
         exit 1
      fi
      rwmsg=1
      zsh_cmd="${zsh_cmd} --rwmsg"
      shift
    ;;
    --help)
      show_help=1
      shift
    ;;
    -c)
      quoted_cmd=$2
      shift 2
    ;;
    *)
     echo "Error Unknown option $arg to rwcli"
     exit 1
  esac
done

if [ -n "${show_help}" ]; then
   zsh_cmd="${zsh_bin} --help"
   exec ${zsh_cmd}
fi

schema_dir="${rift_install}/var/rift/schema"
file_proto_yutil="${rift_install}/usr/bin/rwyangutil"

# Check if the dynamic schema directory exists, if not create it
if [ ! -d ${schema_dir} ]; then
   echo "Creating ${schema_dir} directory..nb schema listing ${schema_listing}"
   ${file_proto_yutil} --lock-file-create --create-schema-dir ${schema_listing} --lock-file-delete
   estat=$?
   if [[ $estat != 0 ]]; then
      echo "Failed to create ${schema_dir} directory"
      exit 1
   fi
fi

if [ -z "${quoted_cmd}" ]; then
  echo ${zsh_cmd}
  exec ${zsh_cmd}
else
  echo ${zsh_cmd} -c \"${quoted_cmd}\"
  exec ${zsh_cmd} -c "${quoted_cmd}"
fi
